/* Copyright (c) 2005-2013 Brocade Communications Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/***************************************************************************
 *   Copyright (C) 2005-2010 Brocade Communications Systems, Inc.          *
 *   All rights reserved.                                                  *
 *   Author : skbalasu                                                     *
 **************************************************************************/

#ifndef NSMGLOBALTYPESH_H
#define NSMGLOBALTYPESH_H

#define NSM_PLUGIN_GLOBAL_VERSION  0

namespace DcmNs
{

    typedef enum
    {
        NSMGLOBALCREATEVLANINTF = 0 ,
        NSMGLOBALUPDATEVLANINTF,
        NSMGLOBALDELETEVLANINTF,
        NSMGLOBALCREATEPOINTF,
        NSMGLOBALUPDATEPOINTF,
        NSMGLOBALDELETEPOINTF,
        NSMGLOBALADDPOTOVLANINTF,
        NSMGLOBALDELETEPOTOVLANINTF,
        NSMGLOBALCREATEPOSTPCONFIG,
        NSMGLOBALDELETEPOSTPCONFIG,
        NSMGLOBALUPDATEPOSTPCONFIG,
        NSMGLOBALADDPHYINTFTOPOINTF,
        NSMGLOBALDELETEPHYINTFTOPOINTF,
        NSMGLOBALCREATEPOVLANSTPCONFIG,
        NSMGLOBALDELETEPOVLANSTPCONFIG,
        NSMGLOBALUPDATEPOVLANSTPCONFIG,
        NSMGLOBALUPDATEPOINSTANCESTPCONFIG,
		NSMGLOBALCREATEVLANCLASSIFIERRULE,
        NSMGLOBALDELETEVLANCLASSIFIERRULE,
        NSMGLOBALUPDATEVLANCLASSIFIERGROUP,
        NSMGLOBALDELETEVLANCLASSIFIERGROUP,
        NSMGLOBALADDVLANCLASSIFIERTOPO,
        NSMGLOBALDELETEVLANCLASSIFIERTOPO,
        NSMGLOBALUPDATELACPCONFIG,
        NSMGLOBALASSOCMACACLPOLICYPOVLANINTF,
        NSMGLOBALASSOCIPACLPOLICYPOVLANINTF,
		NSMGLOBALPBRPOINTF,
		IPPOLICYDELETEGLOBALPBR,
        NSMGLOBALREASSOCMACACLPOLICY,
        NSMGLOBALREASSOCIPACLPOLICY,
        NSMGLOBALDOT1XUPDATECONFIG,
	  	NSMGLOBALQOSPOCONFIG,
		NSMGLOBALQOSPFCCONFIG,
        NSMGLOBALFCOEVLAN,
        NSM_FCOE_WORKER_FCOEPORT_ATTR,
		NSMGLOBALDELETEBRIDGEXSTPCONFIG,
		NSMGLOBALDELETEBRIDGEINSTANCECONFIG,
        NSMGLOBALUPDATEIGMPSVLANCONFIG,
        NSMGLOBALUPDATEIGMPSSGVLANCONFIG,
        NSMGLOBALUPDATEIGMPSMRTRVLANCONFIG,
		NSMGLOBALCREATEINTIPGLOBALCONFIGSP,
		NSMGLOBALCREATEINTSECIPGLOBALCONFIGSP,
		NSMGLOBALDELETEINTSECIPGLOBALCONFIGSP,
        SSMDELETEASSOCIATIONWITHDISCONNECTEDMESSAGE,
		NSMGLOBALQOSMAPCLEANUP,
        NSMGLOBALUPDATEVRRPINTFCONFGLOBAL,
    	NSMGLOBALCOSPROFILEANDTHRESHOLDCONFIG,
		NSMGLOBALOSPFINTERFACECONFIG,
        NSMGLOBALNODEPOMSG,
        NSMGLOBALINTFSVIMSG,
        NSMGLOBALPOIPMSG,
        NSMGLOBALVLANIPMSG,
        NSMGLOBALPIMINTFCFG,
        IGMPPOSVIINTFGLOBALCONFIG,
        IGMPSGINTFGLOBALCONFIG,
        NSMGLOBALINTFLOOPBACKMSG,
		NSMGLOBALELDUPDATECONFIG,
		NSMGLOBALRESERVEDVLAN,
		NSMGLOBALPVLANTRUNKASSOCTOPO,
		NSMGLOBALPVLANMAPPINGTOPO,
		NSMPORTSECURITYGLOBALCONFIGMSG,
		NSMPORTSECURITYPOSTICKYMACMSG,
		SWITCHPORT_VLAN_CONFIG_GLOBAL_MESSAGE,
		MAC_GROUP_CONFIG_GLOBAL_MESSAGE,
		GVLAN_ENABLE_GLOBAL_MESSAGE,

        NSMGLOBALMESSAGE // Leave this line the last
    }NsmGlobal;
      typedef enum
    {
        PROTO_TYPE_UNKNOWN = 0,
        PROTO_TYPE_ARP  = 2054,
        PROTO_TYPE_IPV6 = 34525,
        PROTO_TYPE_IPV4 = 2048
    } ProtoType;
    typedef enum
    {
        ENCAP_TYPE_UNKNOWN = 0,
        ENCAP_TYPE_ETHV2,
        ENCAP_TYPE_SNAPLLC,
        ENCAP_TYPE_NO_SNAPLLC
    } EncapType;
    

    typedef enum {
	    VLAN_UNKNOWN_ACTION = 0,
	    VLAN_CLASSIFIER_ADD_GRP ,
	    VLAN_CLASSIFIER_DEL_GRP
    }vlanClassifierOperation;


    typedef enum
    {
        NSM_FCOE_INVALID,
        NSM_FCOE_CREATE_VLAN,
        NSM_FCOE_DELETE_VLAN,
        NSM_FCOE_UPDATE_VLAN
    } NsmFcoeVlanCmdCode;

    typedef enum
    {
        NSM_VLAN_INTF_TYPE_DEFAULT,
        NSM_VLAN_INTF_TYPE_FCOE
    } NsmVlanIntfType;

     typedef enum
    {
        VLAN_CLASSIFIER_NO_CHOICE = 0,
        VLAN_CLASSIFIER_MAC,
        VLAN_CLASSFIER_PROTO
    }VlanClassifierChoice;
	
}
#endif                                            //NSMGLOBALTYPESH_H
