/* Copyright (c) 2005-2013 Brocade Communications Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/***************************************************************************
 *   Copyright (C) 2013 Brocade Communications Systems, Inc.
 *   All rights reserved.
 *
 *   View definition to hold vlan-ids for physical interfaces
 ***************************************************************************/

#include <vector>

#include "VlanIdForPoPhyIntfView.h"

namespace DcmNs {
    VlanIdForPoPhyIntfView::VlanIdForPoPhyIntfView(NsmLocalObjectManager *pNsmLocalObjectManager)
       :    PrismElement           (pNsmLocalObjectManager),
            PrismPersistableObject(VlanIdForPoPhyIntfView::getClassName()),
            WaveManagedObject          (pNsmLocalObjectManager),
            DcmManagedObject           (pNsmLocalObjectManager),
            WaveLocalManagedObjectBase (this),
            DcmLocalManagedObjectBase  (this),
            DcmLocalManagedObject (pNsmLocalObjectManager),
            WaveManagedView(pNsmLocalObjectManager)
            {
    }

    VlanIdForPoPhyIntfView::~VlanIdForPoPhyIntfView() {

    }
    string VlanIdForPoPhyIntfView::getClassName() {
        return ("VlanIdForPoPhyIntfView");
    }
    void VlanIdForPoPhyIntfView::setupAttributesForPersistence() {
        DcmLocalManagedObjectBase::setupAttributesForPersistence();
        addPersistableAttribute (new AttributeUI32(&_vlanId, ATTR_VLAN_ID));
        addPersistableAttribute (new AttributeString(&_ifName, ATTR_IF_NAME));
    }

    void VlanIdForPoPhyIntfView::setupAttributesForCreate() {
        DcmLocalManagedObjectBase::setupAttributesForCreate();
        addPersistableAttributeForCreate  (new AttributeUI32(&_vlanId, ATTR_VLAN_ID));
        addPersistableAttributeForCreate  (new AttributeString(&_ifName, ATTR_IF_NAME));
    }

    void VlanIdForPoPhyIntfView::setVlanId(const UI32 &vlanId) {
        _vlanId = vlanId;
    }
    UI32 VlanIdForPoPhyIntfView::getVlanId() const {
        return _vlanId;
    }
    void VlanIdForPoPhyIntfView::setIfName(const string &ifName) {
        _ifName = ifName;
    }
    string VlanIdForPoPhyIntfView::getIfName() const {
        return _ifName;
    }

    string VlanIdForPoPhyIntfView::getSqlForCreateView() {
        return
"CREATE OR REPLACE VIEW wavecurrent.VlanIdForPoPhyIntfView AS "
" SELECT * from( "
"SELECT v.id AS vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy, wavecurrent.vlanintfmanagedobject v WHERE phy.swMode = 1 AND v.objectidinstanceid = phy.vlanobjectidinstanceid "
"UNION "
"SELECT v.id, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.pophyintfmanagedobject po, wavecurrent.PhyIntfLocalManagedObject phy, wavecurrent.vlanintfmanagedobject v WHERE v.objectidinstanceid = po.vlanobjectidinstanceid AND po.swMode = 1 AND po.objectidinstanceid = phy.poidinstanceid AND  phy.poidinstanceid IS NOT NULL "
"UNION "
"SELECT pVlanHostPrimVlanId, phy.ifname,  ownerwavenodeobjectidclassid, ownerwavenodeobjectidinstanceid, waveSlotLocalManagedObjectObjectIdclassid, waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy WHERE pVlanHostPrimVlanId != 0 "
"UNION "
"SELECT po.pVlanHostPrimVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid  FROM wavecurrent.pophyintfmanagedobject po, wavecurrent.PhyIntfLocalManagedObject phy WHERE po.pVlanHostPrimVlanId != 0 AND po.objectidinstanceid = phy.poidinstanceid AND  phy.poidinstanceid IS NOT NULL "
"UNION  "
"SELECT pVlanHostSecVlanId, phy.ifname, ownerwavenodeobjectidclassid, ownerwavenodeobjectidinstanceid, waveSlotLocalManagedObjectObjectIdclassid, waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy WHERE pVlanHostSecVlanId != 0    "
"UNION "
"SELECT po.pVlanHostSecVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid  FROM wavecurrent.pophyintfmanagedobject po, wavecurrent.PhyIntfLocalManagedObject phy WHERE po.pVlanHostSecVlanId != 0 AND po.objectidinstanceid = phy.poidinstanceid AND  phy.poidinstanceid IS NOT NULL "
"UNION  "
"SELECT pVlanNativeVlanId, phy.ifname, ownerwavenodeobjectidclassid, ownerwavenodeobjectidinstanceid, waveSlotLocalManagedObjectObjectIdclassid, waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy WHERE pVlanNativeVlanId != 0 "
"UNION "
"SELECT po.pVlanNativeVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid  FROM wavecurrent.pophyintfmanagedobject po, wavecurrent.PhyIntfLocalManagedObject phy WHERE po.pVlanNativeVlanId != 0 AND po.objectidinstanceid = phy.poidinstanceid AND  phy.poidinstanceid IS NOT NULL "
"UNION "
"SELECT nativevlanId, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.NativeVlanIntfConfLocalManagedObject nv, wavecurrent.PhyIntfLocalManagedObject phy WHERE nv.ownermanagedobjectidclassid = phy.objectidclassid AND nv.ownermanagedobjectidinstanceid = phy.objectidinstanceid "
"UNION "
"SELECT nativevlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.NativeVlanIntfConfLocalManagedObject nv, wavecurrent.pointfmanagedobject po, wavecurrent.PhyIntfLocalManagedObject phy WHERE nv.ownermanagedobjectidclassid = po.objectidclassid AND nv.ownermanagedobjectidinstanceid = po.objectidinstanceid AND po.objectidinstanceid = phy.poidinstanceid AND  phy.poidinstanceid IS NOT NULL "
"UNION "
"SELECT pvta.primaryVlanId, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid  FROM wavecurrent.PVlanTrunkAssocManagedObject pvta, wavecurrent.phyintflocalmanagedobject phy  WHERE pvta.ownermanagedobjectidclassid = phy.objectidclassid AND pvta.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION "
"SELECT pvta.primaryVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PVlanTrunkAssocManagedObject pvta, wavecurrent.pointfmanagedobject po, wavecurrent.phyintflocalmanagedobject phy  WHERE pvta.ownermanagedobjectidclassid = phy.poidclassid AND pvta.ownermanagedobjectidinstanceid = phy.poidinstanceid AND phy.poidinstanceid = po.objectidinstanceid  "
"UNION "
"SELECT pvta.secondaryVlanId, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PVlanTrunkAssocManagedObject pvta, wavecurrent.phyintflocalmanagedobject phy WHERE pvta.ownermanagedobjectidclassid = phy.objectidclassid AND pvta.ownermanagedobjectidinstanceid = phy.objectidinstanceid "
"UNION "
"SELECT pvta.secondaryVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PVlanTrunkAssocManagedObject pvta, wavecurrent.pointfmanagedobject po, wavecurrent.phyintflocalmanagedobject phy WHERE pvta.ownermanagedobjectidclassid = phy.poidclassid AND pvta.ownermanagedobjectidinstanceid = phy.poidinstanceid AND phy.poidinstanceid = po.objectidinstanceid  "
"UNION "
"SELECT pvm.primaryVlanId, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PVlanMappingManagedObject pvm, wavecurrent.phyintflocalmanagedobject phy WHERE pvm.ownermanagedobjectidclassid = phy.objectidclassid AND pvm.ownermanagedobjectidinstanceid = phy.objectidinstanceid "
"UNION "
"SELECT pvm.primaryVlanId, po.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PVlanMappingManagedObject pvm, wavecurrent.pointfmanagedobject po, wavecurrent.phyintflocalmanagedobject phy WHERE pvm.ownermanagedobjectidclassid = phy.poidclassid AND pvm.ownermanagedobjectidinstanceid = phy.poidinstanceid AND phy.poidinstanceid = po.objectidinstanceid  "
"UNION "
"SELECT phy.rspan_accessvlan, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy WHERE phy.rspan_accessvlan != 1 "
"UNION "
"SELECT mavc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.macaddressvlanclassificationmo mavc, wavecurrent.phyintflocalmanagedobject phy WHERE mavc.ownermanagedobjectidclassid = phy.objectidclassid AND mavc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT mgvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.macgroupvlanclassificationmo mgvc, wavecurrent.phyintflocalmanagedobject phy WHERE mgvc.ownermanagedobjectidclassid = phy.objectidclassid AND mgvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT cvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.ctagvlanclassificationmo cvc, wavecurrent.phyintflocalmanagedobject phy WHERE cvc.ownermanagedobjectidclassid = phy.objectidclassid AND cvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT cpvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.ctagpvlanclassificationmo cpvc, wavecurrent.phyintflocalmanagedobject phy WHERE cpvc.ownermanagedobjectidclassid = phy.objectidclassid AND cpvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT mavc.vlanid, pophy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.macaddressvlanclassificationmo mavc, wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE mavc.ownermanagedobjectidclassid = phy.poidclassid AND mavc.ownermanagedobjectidinstanceid = phy.poidinstanceid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION  "
"SELECT mgvc.vlanid, pophy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.macgroupvlanclassificationmo mgvc, wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE mgvc.ownermanagedobjectidclassid = phy.poidclassid AND mgvc.ownermanagedobjectidinstanceid = phy.poidinstanceid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION  "
"SELECT cvc.vlanid, pophy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.ctagvlanclassificationmo cvc, wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE cvc.ownermanagedobjectidclassid = phy.poidclassid AND cvc.ownermanagedobjectidinstanceid = phy.poidinstanceid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION  "
"SELECT cpvc.vlanid, pophy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.ctagpvlanclassificationmo cpvc, wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE cpvc.ownermanagedobjectidclassid = phy.poidclassid AND cpvc.ownermanagedobjectidinstanceid = phy.poidinstanceid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION  "
"SELECT marvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.rspanmacaddressvlanclassificationmo marvc, wavecurrent.phyintflocalmanagedobject phy WHERE marvc.ownermanagedobjectidclassid = phy.objectidclassid AND marvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT mgrvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.rspanmacgroupvlanclassificationmo mgrvc, wavecurrent.phyintflocalmanagedobject phy WHERE mgrvc.ownermanagedobjectidclassid = phy.objectidclassid AND mgrvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid "
"UNION  "
"SELECT crvc.vlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.rspangvlantrunkportmanagedobject crvc, wavecurrent.phyintflocalmanagedobject phy WHERE crvc.ownermanagedobjectidclassid = phy.objectidclassid AND crvc.ownermanagedobjectidinstanceid = phy.objectidinstanceid  "
"UNION  "
"SELECT span.destvlanid, phy.ifname, phy.ownerwavenodeobjectidclassid, phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid FROM wavecurrent.PhyIntfLocalManagedObject phy,wavecurrent.spanglobalconfigmanagedobject span WHERE span.source_ifname = phy.ifname "
"UNION "
"select vpc.accessVlan, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 "
"UNION "
"select vpc.accessVlan, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select vpc.accessVlan, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 "
"UNION "
"select vpc.accessVlan, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy,   wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select vpmo.accessvlan, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy  where phy.isPortProfiled = 't' and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' "
"UNION "
"select vpmo.accessvlan, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.pophyintfmanagedobject pophy  where (pophy.isPortProfiled = 't'  and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid) and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' "
"UNION "
"select nativeVlanMo.nativevlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMNativeVlanManagedObject nativeVlanMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=2 and nativeVlanMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select nativeVlanMo.nativevlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMNativeVlanManagedObject nativeVlanMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=2 and nativeVlanMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select nativeVlanMo.nativevlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMNativeVlanManagedObject nativeVlanMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=2 and nativeVlanMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select nativeVlanMo.nativevlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMNativeVlanManagedObject nativeVlanMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=2 and nativeVlanMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select nativeVlanMo.nativevlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMNativeVlanManagedObject nativeVlanMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy  where phy.isPortProfiled = 't' and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '2' and nativeVlanMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid "
"UNION "
"select nativeVlanMo.nativevlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMNativeVlanManagedObject nativeVlanMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.pophyintfmanagedobject pophy  where (pophy.isPortProfiled = 't'  and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid) and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '2' and nativeVlanMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid "
"UNION "
"select macMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacAddressVlanClassificationMO macMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select macMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacAddressVlanClassificationMO macMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select macMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacAddressVlanClassificationMO macMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select macMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacAddressVlanClassificationMO macMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select macClassificationMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMMacAddressVlanClassificationMO macClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy  where phy.isPortProfiled = 't' and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' and macClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid "
"UNION "
"select macClassificationMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMMacAddressVlanClassificationMO macClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.pophyintfmanagedobject pophy  where (pophy.isPortProfiled = 't'  and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid) and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' and macClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid " 
"UNION "
"select macMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacGroupVlanClassificationMO macMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select macMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacGroupVlanClassificationMO macMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select macMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacGroupVlanClassificationMO macMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select macMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMMacGroupVlanClassificationMO macMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=1 and macMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select macGroupClassificationMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMMacGroupVlanClassificationMO macGroupClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy  where phy.isPortProfiled = 't' and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' and macGroupClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid "
"UNION "
"select macGroupClassificationMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMMacGroupVlanClassificationMO macGroupClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.pophyintfmanagedobject pophy  where (pophy.isPortProfiled = 't'  and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid) and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '1' and macGroupClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid  "
"UNION "
"select ctagMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMCtagVlanClassificationMO ctagMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=2 and ctagMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select ctagMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofilecompositemanagedobject pd, wavecurrent.profilemanagedobject ppmo,wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMCtagVlanClassificationMO ctagMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofilename = ppmo.profilename and ppmo.profilename = vpc.description and vpc.swMode=2 and ctagMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select ctagMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from  wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMCtagVlanClassificationMO ctagMo where phy.isPortProfiled = 'f' and phy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=2 and ctagMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid "
"UNION "
"select ctagMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid  from wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.amppprofiledomaincompositemanagedobject pd, wavecurrent.profiledomainmanagedobject pdmo, wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.vlanprofilecfgmanagedobject vpc, wavecurrent.APPMCtagVlanClassificationMO ctagMo where pophy.isPortProfiled = 'f' and pophy.objectidinstanceid = pd.ownermanagedobjectidinstanceid and pd.portprofiledomainname = pdmo.portprofiledomainname and pdmo.objectidinstanceid = pdc.ownermanagedobjectidinstanceid and pdc.portprofilename = vpc.description and vpc.swMode=2 and ctagMo.ownermanagedobjectidinstanceid = vpc.objectidinstanceid and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid "
"UNION "
"select ctagClassificationMo.vlanId, phy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMCtagVlanClassificationMO ctagClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy  where phy.isPortProfiled = 't' and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '2' and ctagClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid "
"UNION "
"select ctagClassificationMo.vlanId, pophy.ifname, phy.ownerwavenodeobjectidclassid,phy.ownerwavenodeobjectidinstanceid, phy.waveSlotLocalManagedObjectObjectIdclassid, phy.waveSlotLocalManagedObjectObjectIdinstanceid from wavecurrent.APPMCtagVlanClassificationMO ctagClassificationMo, wavecurrent.vlanprofilecfgmanagedobject vpmo, wavecurrent.phyintflocalmanagedobject phy, wavecurrent.pophyintfmanagedobject pophy  where (pophy.isPortProfiled = 't'  and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid) and vpmo.description in (select distinct pdc.portprofilename from wavecurrent.profiledomaincompositemanagedobject pdc, wavecurrent.profiledomainmanagedobject pdmo where pdc.ownermanagedobjectidclassid = pdmo.objectidclassid and pdc.ownermanagedobjectidinstanceid = pdmo.objectidinstanceid and pdmo.portprofiledomainname = 'default') and (exists (SELECT isPortProfiled FROM wavecurrent.phyintflocalmanagedobject WHERE isPortProfiled = 't') or exists (SELECT pophy.isPortProfiled FROM wavecurrent.pophyintfmanagedobject pophy, wavecurrent.phyintflocalmanagedobject phy WHERE pophy.isPortProfiled = 't' and pophy.objectidclassid = phy.poidclassid AND pophy.objectidinstanceid = phy.poidinstanceid)) and vpmo.swmode = '2' and ctagClassificationMo.ownermanagedobjectidinstanceid = vpmo.objectidinstanceid  "
") AS dummy where vlanId != 0 "
"; "
;
    }
}
