/* Copyright (c) 2005-2013 Brocade Communications Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/***************************************************************************
 *   Copyright (C) 2005-2008 Brocade Communications Systems, Inc.          *
 *   All rights reserved.                                                  *
 *   Author : Vidyasagara Reddy Guntaka                                    *
 ***************************************************************************/

#include "Framework/Utils/WaveSourceGenerator/WaveSourceGeneratorForMessage.h"

namespace WaveNs
{

WaveSourceGeneratorForMessage::WaveSourceGeneratorForMessage (const string &name, const string &nameSpace)
    : WaveSourceGeneratorBase (name, nameSpace)
{
}

WaveSourceGeneratorForMessage::~WaveSourceGeneratorForMessage ()
{
}

string WaveSourceGeneratorForMessage::generateClassName () const
{
    return (m_name + "Message");
}

string WaveSourceGeneratorForMessage::generateHIncludes () const
{
    string hIncludes = "#include \"Framework/Messaging/Local/PrismMessage.h\"\n"
                       "\n";

    return (hIncludes);
}

string WaveSourceGeneratorForMessage::generateHClassBegin () const
{
    string classBegin = "class " + generateClassName () + " : public PrismMessage\n"
                        "{\n";

    return (classBegin);
}

string WaveSourceGeneratorForMessage::generateHClassMemberFunctionsPrivate () const
{
    string memberFunctionsPrivate = "    private :\n"
                                    "        void setupAttributesForSerialization ();\n"
                                    "\n";

    return (memberFunctionsPrivate);
}

string WaveSourceGeneratorForMessage::generateHClassMemberFunctionsPublic () const
{
    string memberFunctionsPublic = "    public :\n"
                                   "                 " + generateClassName () + " ();\n"
                                   "        virtual ~" + generateClassName () + " ();\n";

    return (memberFunctionsPublic);
}

string WaveSourceGeneratorForMessage::generateCppMemberFunctions () const
{
    string memberFunctions;

    memberFunctions += generateClassName () + "::" + generateClassName () + " ()\n"
                       "    : PrismMessage (<OMID>, <OPCODE>)\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += generateClassName () + "::~" + generateClassName () + " ()\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += "void " + generateClassName () + "::setupAttributesForSerialization ()\n"
                       "{\n"
                       "    PrismMessage::setupAttributesForSerialization ();\n"
                       "\n"
                       "    // This class Specific Attributes below\n"
                       "    <AUTOGENERATED : FILLME>\n"
                       "}\n"
                       "\n";

    return (memberFunctions);
}

}
