/* Copyright (c) 2005-2013 Brocade Communications Systems, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/***************************************************************************
 *   Copyright (C) 2005-2008 Brocade Communications Systems, Inc.          *
 *   All rights reserved.                                                  *
 *   Author : Vidyasagara Reddy Guntaka                                    *
 ***************************************************************************/

#include "Framework/Utils/WaveSourceGenerator/WaveSourceGeneratorForManagedObject.h"

namespace WaveNs
{

WaveSourceGeneratorForManagedObject::WaveSourceGeneratorForManagedObject (const string &name, const string &nameSpace)
    : WaveSourceGeneratorBase (name, nameSpace)
{
}

WaveSourceGeneratorForManagedObject::~WaveSourceGeneratorForManagedObject ()
{
}

string WaveSourceGeneratorForManagedObject::generateClassName () const
{
    return (m_name);
}

string WaveSourceGeneratorForManagedObject::generateHIncludes () const
{
    string hIncludes = "#include \"Framework/ObjectModel/WaveManagedObject.h\"\n"
                       "\n";

    return (hIncludes);
}

string WaveSourceGeneratorForManagedObject::generateHClassBegin () const
{
    string classBegin = "class " + generateClassName () + " : public WaveManagedObject\n"
                        "{\n";

    return (classBegin);
}

string WaveSourceGeneratorForManagedObject::generateHClassMemberFunctionsPrivate () const
{
    string memberFunctionsPublic = "    private :\n"
                                   "        void setupAttributesForPersistence ();\n"
                                   "        void setupAttributesForCreate      ();\n"
                                   "\n";

    return (memberFunctionsPublic);
}

string WaveSourceGeneratorForManagedObject::generateHClassMemberFunctionsPublic () const
{
    string memberFunctionsPublic = "    public :\n"
                                   "                 " + generateClassName () + " (WaveObjectManager *pWaveObjectManager);\n"
                                   "        virtual        ~" + generateClassName () + " ();\n"
                                   "\n"
                                   "        static  string  getClassName ();\n";

    return (memberFunctionsPublic);
}

string WaveSourceGeneratorForManagedObject::generateCppMemberFunctions () const
{
    string memberFunctions;

    memberFunctions += generateClassName () + "::" + generateClassName () + " (WaveObjectManager *pWaveObjectManager)\n"
                       "    : PrismElement           (pWaveObjectManager),\n"
                       "      PrismPersistableObject (" + generateClassName () + "::getClassName (), WaveManagedObject::getClassName ()),\n"
                       "      WaveManagedObject     (pWaveObjectManager)\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += generateClassName () + "::~" + generateClassName () + " ()\n"
                       "{\n"
                       "}\n"
                       "\n";

    memberFunctions += "void " + generateClassName () + "::getClassName ()\n"
                       "{\n"
                       "    return (\"" + generateClassName () + "\");\n"
                       "}\n"
                       "\n";

    memberFunctions += "void " + generateClassName () + "::setupAttributesForPersistence ()\n"
                       "{\n"
                       "    WaveManagedObject::setupAttributesForPersistence ();\n"
                       "\n"
                       "    // This class Specific Attributes below\n"
                       "    <AUTOGENERATED : FILLME>\n"
                       "}\n"
                       "\n";

    memberFunctions += "void " + generateClassName () + "::setupAttributesForCreate ()\n"
                       "{\n"
                       "    WaveManagedObject::setupAttributesForCreate ();\n"
                       "\n"
                       "    // This class Specific Attributes below\n"
                       "    <AUTOGENERATED : FILLME>\n"
                       "}\n"
                       "\n";

    return (memberFunctions);
}

}
